spring.application.name=API
server.port=8089
spring.data.mongodb.uri=mongodb+srv://waneexw:XSxVcaOGZGwcTHv7@analyticscluster.f88yl.mongodb.net/Analytics?retryWrites=true&w=majority

spring.data.mongodb.database=Analytics